version: "3.3"

services:
  api:
    build: ./webapp-api
    ports:
      - 4000:4000
    environment:
    - REDIS_HOST=redis
    - DRIVER_HOST=driver:3000

  driver:
    build:
      context: ./my_node_openzwave
    environment:
    - REDIS_HOST=redis
    command: yarn start

  redis:
    image: redis:latest
