version: "3.3"

services:
  driver:
    volumes:
    - ./driver/config/config.json:/etc/config.json:ro
    devices:
    - /dev/ttyUSB0

    restart: unless-stopped
    command: yarn start live --config /etc/config.json
  api:
    restart: unless-stopped
  redis:
    restart: unless-stopped
