version: "3.3"

services:
  elm:
    build: ./webapp-frontend
    volumes:
      - ./webapp-frontend:/app

  nginx:
    build: nginx
    ports:
      - 8080:80
    volumes:
      - ./webapp-frontend/out:/usr/share/nginx/html:ro
    depends_on:
      - api

  api:
    volumes:
      - ./webapp-api:/app

  driver:
    volumes:
      - ./my_node_openzwave:/driver

  redis:
    image: redis:latest
